_BASE_: "multimask_rcnn_R_50_FPN_1x.yaml"
MODEL:
  WEIGHTS: "output/model_final.pth"
DATASETS:
  TEST: ("tablewares",)
TEST:
  EXPECTED_RESULTS: [["bbox", "AP", 47.34, 0.02], ["segm", "AP",  42.67, 0.02], ["bbox_TTA", "AP", 49.11, 0.02], ["segm_TTA", "AP", 45.04, 0.02]]
  AUG:
    ENABLED: True
    MIN_SIZES: (700, 800)  # to save some time
